apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  namespace: apps
  labels:
    app: shared
  annotations:
    description: "ConfigMap compartilhado com variáveis de configuração para os serviços do projeto."
data:
  # Redis (namespace "database")
  REDIS_ADDRESS: "redis.database.svc.cluster.local"
  REDIS_PORT: "6379"
  # Elasticsearch (namespace "database")
  ELASTICSEARCH_URI: "http://elasticsearch.database.svc.cluster.local:9200"
  ELASTICSEARCH_INDEX: "games"

  # LocalStack (namespace "localstack")
  LOCALSTACK_ENDPOINT: "http://localstack.localstack.svc.cluster.local:4566/"

  #SQS
  SQS_SERVICE_URL: "http://localstack.localstack.svc.cluster.local:4566"
  SQS_EMAIL_QUEUE_URL: "http://localstack.localstack.svc.cluster.local:4566/000000000000/notification-queue"
  SQS_DONATION_QUEUE_URL: "http://localstack.localstack.svc.cluster.local:4566/000000000000/process-donation-payment"

  #SNS
  SNS_SERVICE_URL: "http://localstack.localstack.svc.cluster.local:4566"
