apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  labels:
    app: shared
  annotations:
    description: "ConfigMap compartilhado com variáveis de configuração para os serviços do projeto."
data:
  # Redis
  REDIS_ADDRESS: "redis"
  REDIS_PORT: "6379"
  # Elasticsearch
  ELASTICSEARCH_URI: "http://elasticsearch:9200"
  ELASTICSEARCH_INDEX: "games"

  # LocalStack
  LOCALSTACK_ENDPOINT: "http://localstack:4566/"
  
  #SQS
  SQS_SERVICE_URL: "http://localstack:4566"
  SQS_EMAIL_QUEUE_URL: "http://localstack:4566/000000000000/notification-queue"

  #SNS
  SNS_SERVICE_URL: "http://localstack:4566"