apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: localstack-pvc
  namespace: localstack
  labels:
    app: localstack
  annotations:
    description: "PVC para persistir os dados do LocalStack em desenvolvimento local."

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 5Gi
