apiVersion: v1
kind: Secret

metadata:
  name: localstack-secret
  labels:
    app: localstack
  annotations:
    description: "Secret com credenciais do LocalStack."

type: Opaque

stringData:
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  AWS_SESSION_TOKEN: ""
  LOCALSTACK_AUTH_TOKEN: "ls-mIJONAcA-pitI-wacE-0014-0992hamOe092"
  #NEW_RELIC_LICENSE_KEY_LAMBDA: "4f8eab81ae33b9bdcf1dc52569843322e51fNRAL"