apiVersion: v1
kind: Service

metadata:
  name: localstack
  labels:
    app: localstack
  annotations:
    description: "Service do LocalStack para acesso interno e local via NodePort."

spec:
  type: NodePort
  selector:
    app: localstack

  ports:
    - name: edge
      port: 4566
      targetPort: 4566
      nodePort: 30466
