apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-storage
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 10Gi