apiVersion: v1
kind: Service

metadata:
  name: donation-api
  namespace: apps

  labels:
    app: donation-api

  annotations:
    description: "Service para a API de Catálogo, expondo a porta 80 para acesso interno no cluster."

spec:
  type: NodePort

  selector:
    app: donation-api
  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30083
  

# acessar localmente: http://localhost:30083/