apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc-campanha
  
  labels:
    app: postgresdb-campanha
  
  annotations:
    description: "PersistentVolumeClaim para o banco de dados PostgreSQL da API de Campanha, garantindo armazenamento persistente para os dados do banco mesmo que o pod seja reiniciado ou recriado."

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi