apiVersion: v1
kind: Service

metadata:
  name: pgadmin

  labels:
    app: pgadmin
  
  annotations:
    description: "Service para o PgAdmin, permitindo que outros pods no cluster se comuniquem com o PgAdmin usando o nome do servi�o como hostname."

spec:
  type: NodePort

  selector:
    app: pgadmin

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090

# acessar localmente: http://localhost:30090  