apiVersion: v1
kind: ConfigMap

metadata:
  name: pgadmin-config

data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Campanha DB",
          "Group": "Databases",
          "Host": "postgresdb-campanha",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgresAdmin",
          "SSLMode": "prefer"
        }
      }
    }