apiVersion: v1
kind: Service

metadata:
  name: elasticsearch
  labels:
    app: elasticsearch

  annotations:
    description: "Service para o Elasticsearch, expondo a porta 9200 para a busca avançada do catálogo."

spec:
  type: ClusterIP

  selector:
    app: elasticsearch

  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: http

  clusterIP: None
