apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: elasticsearch-pvc

  labels:
    app: elasticsearch

  annotations:
    description: "PersistentVolumeClaim para o Elasticsearch, garantindo persistência do índice de busca mesmo que o pod seja reiniciado ou recriado."

spec:
  accessModes:
    - ReadWriteOnce
    
  storageClassName: auto-ebs-sc

  resources:
    requests:
      storage: 10Gi
