apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    app: grafana
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  claimRef:
    namespace: monitoring
    name: grafana-storage
  hostPath:
    path: /tmp/monitoring-grafana
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    app: prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  claimRef:
    namespace: monitoring
    name: prometheus-pvc
  hostPath:
    path: /tmp/monitoring-prometheus
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tempo-pv
  labels:
    app: tempo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  claimRef:
    namespace: monitoring
    name: tempo-storage
  hostPath:
    path: /tmp/monitoring-tempo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-postgres-pv
  labels:
    app: postgres-zabbix
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  claimRef:
    namespace: monitoring
    name: postgres-pvc
  hostPath:
    path: /tmp/monitoring-zabbix-postgres
