apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users-api
  annotations:
    description: "Deployment para a API de Usuários, garantindo alta disponibilidade e escalabilidade para o serviço de gerenciamento de usuários."

spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: users-api
  
  template:
    metadata:
      labels:
        app: users-api
    
    spec:
      containers:
        - name: users
          image: projetofiap/users-api:latest
          
          ports:
            - containerPort: 8080
          
          resources:
            requests: # recursos mínimos
              memory: "128Mi"
              cpu: "250m"
            
            limits: # recursos máximos
              memory: "256Mi"
              cpu: "500m"

          env:
            # SQS
            - name: SqsSettings__Region
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: SQS_REGION

            - name: SqsSettings__AccessKey
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: SQS_ACCESS_KEY

            - name: SqsSettings__SecretKey
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: SQS_SECRET_KEY

            - name: SqsSettings__ServiceURL
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: SQS_SERVICE_URL

            - name: SqsSettings__EmailQueueURL
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: SQS_EMAIL_QUEUE_URL                  
            
            # Db
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: DB_USER_CONNECTION_STRING
                  
            # Firebase
            - name: Firebase__CredentialPath
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: FIREBASE_CREDENTIAL_PATH
                  
            - name: Firebase__ApiKey
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: FIREBASE_APIKEY